version: '3.8'

services:
  livekit-server:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit/config.yaml
    ports:
      - "7880:7880"     # API e WebSocket
      - "7881:7881"     # TCP port (fallback)
      - "7935:7935"     # RTC UDP
      - "50000-60000:50000-60000/udp"  # UDP ports para WebRTC
    volumes:
      - ./livekit.yaml:/etc/livekit/config.yaml
    environment:
      - LIVEKIT_DEBUG=true
      - LIVEKIT_DEVELOPMENT=true
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - livekit-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass livekit
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - livekit-network

networks:
  livekit-network:
    driver: bridge

volumes:
  redis_data:
